Leaving game - unmute players
pedrofracassi/amongcord pull request #4
Opened 2020-09-11 19:33 UTC by dilson-pieve

I noticed that when we use the command 'endgame' the players kept muted. Then I'm adding this code to fix that. I didn't test.

2020-09-11 19:41 UTC, pedrofracassi requested changes

2020-09-11 19:41 UTC, pedrofracassi commented on src/GameManager.js
> +    Game.players.forEach(player => {
That wouldn't work. You'd have to `this.getGame(guildId)` instead of using plain `Game`

2020-09-11 19:41 UTC, pedrofracassi commented
Nice catch! I've requested some changes, if you could please take a look :)

2020-09-11 20:42 UTC, dilson-pieve commented
Changes done, thanks

2020-09-15 01:47 UTC, pedrofracassi commented
Thank you so much for the PR. I'm going to close this as I ended up implementing it myself after some major code changes.

2020-09-15 01:47 UTC, closed without merging